---
title: ""
format:
  pdf:
    include-in-header:
      - estilos/estilo-legal.tex
    header-includes: |
      \newcommand{\numero}{$2$}
      \newcommand{\volumen}{$1$}
      \newcommand{\anio}{$2026$}
      \newcommand{\issn}{$XXXX-XXXX$}
      \newcommand{\size}{0.0mb}
    toc: false
    number-sections: false
---

**An@lítica.**
Revista de la División de Ciencias Sociales y Humanidades, UAM-Lerma\
**Contacto**: 

**UNIVERSIDAD AUTÓNOMA METROPOLITANA, UNIDAD LERMA**

*Dr. Gabriel Sóto Córtes*\
Rector\
*Dra. Alma Patricia de León Calderón*\
Secretaria\
*Dr. Raúl Hernández Mar*\
Director de la División de Ciencias Sociales y Humanidades\
*Dra. Ana Carolina Robles Salvador*\
Secretaria Académica de la División de Ciencias Sociales y Humanidades\

**COMITÉ EDITORIAL DE CIENCIAS SOCIALES Y HUMANIDADES**\
PUBLICACIONES PERIÓDICAS

*Abigail Martínez Mendoza*\
Coordinadora General\
*Omar Valencia Dominguez*\
Departamento de Procesos Sociales\
*Hugo Solís García*\
Departamento de Arte y Humanidades\
*José Omar Pérez Baños*\
Departamento de Estudios Culturales\

**EDICIÓN TÉCNICA Y CORRECCIÓN DE ESTILO**\
*Jonathan Armando Chaves Solis y José Omar Pérez Baños*

---

\footnotesize \textbf{An@lítica} nueva época,  núm. \numero, vol. \volumen, \anio, es una publicación de la Universidad Autónoma Metropolitana a través de la Unidad Lerma, División de Ciencias Sociales y Humanidades. Av. Prolongación Canal de Miramontes 3855, Colonia Rancho Los Colorines, Alcaldía Tlalpan, C.P. 14386, Ciudad de México y Av. de las Garzas No. 10, Colonia El Panteón, Lerma de Villada, Municipio de Lerma, Estado de México, C.P. 52005. Teléfono: 728 282 7002. Certificado de Reserva de Derechos al Uso Exclusivo **en trámite**. ISSN **en trámite**, ambos otorgados por el Instituto Nacional del Derecho de Autor. Responsable de la última actualización de este número: José Omar Pérez Baños. Tamaño del archivo: \size.

La revista se encuentra disponible en acceso abierto en la página: <http://revista-csh.ler.uam.mx/index.php/rda>

**Nota importante**: Las expresiones vertidas por los autores no necesariamente reflejan la postura del editor de la publicación.

**Derechos de reproducción**: Queda estrictamente prohibida la reproducción total o parcial de los contenidos e imágenes de la publicación sin previa autorización de la Universidad Autónoma Metropolitana.
