---
# Metadatos ESENCIALES del capítulo
pdf-engine: xelatex
title: "Eduardo Restrepo, antropólogo"
subtitle: ""  # Vacío para entrevistas
author:
  - name: "Ignacio Moreno López"  # Quien realiza la entrevista
    affiliation: "Universidad Autónoma Metropolitana, Unidad Lerma"
    email: " i.lopez@correo.ler.uam.mx."
    correspondence: true

# Metadatos ESPECÍFICOS
chapter-number: "X"
page-range: ""
doi: ""

# Contenido del capítulo
resumen: |
  Eduardo Restrepo es antropólogo colombiano egresado de la Universidad de Antioquia (Medellín, 1996), con estudios de maestría y doctorado en la University of Carolina del Norte en Chapel Hill. Dentro de sus líneas de investigación se destacan los estudios referidos a las poblaciones afrocolombianas, con particular interés en la región del Pacífico colombiano. Los procesos de etnización y racialización, así como las políticas de la representación y subjetividades políticas negras, son algunos de los asuntos abordados en sus publicaciones. También se ha interesado por las geopolíticas del conocimiento y los procesos de lugarización que configuran campos disciplinarios como el de la antropología o transdisciplinarios como el de los estudios culturales. El objetivo de la entrevista es dar a conocer la diversidad de la práctica científica a través de entrevistas abiertas que rescaten la vida y devenir de personas relevantes de las ciencias sociales.

keywords:
  - "Estudios Culturales"
  - "Subjetividades"
  - "Antropología Crítica"
  - "entrevista"  # Agregue esta palabra clave

# Tipo de documento
type: chapter

# Campos OPCIONALES
acknowledgments: ""
funding: ""
notes: ""
---

\addtocontents{toc}{\protect\hspace{1.5em}Ignacio Moreno López\par}
\markboth{Entrevista a Eduardo Restrepo}{}

\begin{flushright}
\Large Ignacio Moreno López\footnote{SEMBLANZA}
\end{flushright}

---

\begingroup
\footnotesize

Eduardo Restrepo es antropólogo colombiano egresado de la Universidad de Antioquia (Medellín, 1996), con estudios de maestría y doctorado en la University of Carolina del Norte en Chapel Hill. Dentro de sus líneas de investigación se destacan los estudios referidos a las poblaciones afrocolombianas, con particular interés en la región del Pacífico colombiano. Los procesos de etnización y racialización, así como las políticas de la representación y subjetividades políticas negras, son algunos de los asuntos abordados en sus publicaciones. También se ha interesado por las geopolíticas del conocimiento y los procesos de lugarización que configuran campos disciplinarios como el de la antropología o transdisciplinarios como el de los estudios culturales.

El objetivo de la entrevista es dar a conocer la diversidad de la práctica científica a través de entrevistas abiertas que rescaten la vida y devenir de personas relevantes de las ciencias sociales.
\endgroup

---

\begin{transcripcion}
\item \personaje{Ignacio} Muy buenas tardes a todas a todos y todes es bienvenidos a esta charla en la que hoy vamos a sentarnos con un colega y amigo Eduardo Restrepo. Quienes no tengan la suerte de conocer a Eduardo, que es una persona polifacética muy viajera y que ha hecho una de las grandes contribuciones a las rupturas y a los avances en determinados espacios, les voy a comentar que actualmente es un investigador adjunto del Centro de Investigación, Innovación y Creación de la Universidad Católica de Temuco y es profesor del doctorado de antropología de la misma universidad. Su formación es como antropólogo colombiano egresó hace ya unos añitos de hecho, creo que en breve van a ser 30 años si no me equivoco porque creo que egresaste en el 96 de la Universidad de Antioquia en Medellín. Para quienes no conozcan Colombia, es una de las principales ciudades del país y tuvo la oportunidad en su momento de realizar unos estudios de maestría y doctorado en la Universidad de Carolina del Norte en Chapel Hill. Además, fue presidente entre el 2015 y 2020 de la Asociación Latinoamericana de Antropología. Actualmente es profesor en diferentes universidades. Ya veréis a lo largo de la charla, que es una persona muy cercana a lo que llaman ciudadano del mundo en cuanto a su movilidad, en cuanto a su visión de la realidad y en cuanto a la apertura. Pues primeramente Eduardo agradecerte muchísimo esta entrevista que nos permitas entrar en tu vida y en tu mundo.

\item \personaje{Eduardo} Gracias a ti por la invitación y ya qué bueno que estemos conversando nuevamente.

\item \personaje{Ignacio} Sí, para quienes no sepan, ya tuvimos una entrevista que tristemente se perdió el audio, pero bueno eso nos da la excusa para volver un año después para volver a sentarnos a tomar un cafecito y a charlar un poco. Eduardo una cosa que interesa siempre a nuestro alumnado y a nuestros colegas obviamente nos interesa ¿quién es Eduardo hoy día? pero ¿quién fue Eduardo? ¿por qué Eduardo es quién es? porque en qué momento o qué recuerdos y de Medellín de tu infancia de esos primeros momentos que dijeron que fueron marcando un poco hacia dónde iría tu vida cuéntanos un poco cómo era la Medellín de los 80 qué tipo de vida, porque por desgracia pues ehh toda Colombia es consciente de los estereotipos no... de cómo tenemos predefinida por series de televisión y por literatura panfletaria la vida no, pero ¿cuál es la cotidianidad real o cuál es la cotidianidad que tú recuerdas de ese mundo?

\item \personaje{Eduardo} Yo nací en un barrio popular en Medellín que sigue mucho las características que estás mencionando: sí había bastante violencia. Crecí en uno de los barrios donde muchos de nosotros aspiramos a ser sicarios cuando teníamos 12 o 13 años de edad, donde Pablo Escobar era un referente de las armas, de muchas cosas... Pero también recuerdo mucho de haber crecido en la calle jugando con muchos amigos, jugando al fútbol, yendo a nadar. Para mí el recuerdo de la infancia de ese barrio popular es el un barrio muy lleno de cariño, de amistad, de mucha gente, de mucha música, de empatía, y a pesar de que era muy duro y muchos de quienes crecieron conmigo terminaron asesinados o terminaron en cruces o en la cárcel, de todas maneras, mi recuerdo es una experiencia muy cargada de historias muy llenas de afecto y también muy llenas de fuerza. Nuestros papás y mamás trabajaban en fábricas o trataban de rebuscarse la vida por diferentes lados. Yo fui la primera persona de mi familia que fue a la universidad a estudiar, algo como antropología donde me encontré con muchas conversaciones muy interesantes más allá de lo que se vivía en un barrio lleno de fútbol, de música salsa, de fierros y tropeles, pero también de mucha alegría y cariño.

\item \personaje{Ignacio} Era muy mexicano también.

\item \personaje{Eduardo} Es parecido a lo que ustedes están viviendo ahora.

\item \personaje{Ignacio} De hecho, una de las cosas que vemos en nuestra universidad es que tenemos la fortuna de muchos del alumnado que son la primera generación que llega a la universidad, ¿cómo vivió tu casa ese momento? en el que Eduardo dice no, pues yo voy a estudiar. O sea yo no voy a la fábrica, yo no voy a un taller, sino que voy a ir a la universidad, y además voy a estudiar una cosa y se llama antropología. No voy a estudiar ingeniería no voy a estudiar medicina no voy a estudiar derecho, no, ¿cómo fue esa situación? ¿recuerdas?

\item \personaje{Eduardo} Pues fue bastante curiosa. Recuerdo que uno de mis tíos, cuando supo que iba a la universidad, me recomendó que estudiara ingeniería química para que hiciera coca. Estudiar antropología obviamente era algo que no que no que cabía en el horizonte de sentido de la familia. En ese momento también yo estoy saliendo de la casa y me fui a vivir solo por un tiempo. En esa época no había tanta la presión de qué iba a hacer en términos laborales o de lo que venía más adelante. Desde hacía algunos años, hacia el final de mi secundaria, venía trabajando con una agrupación de izquierda, donde leíamos a Freud y a Marx y que estábamos interesados en al trabajo político en el barrio y en otros escenarios. Entonces para mí el asunto de estudiar antropología hacía parte más de un proceso de vida donde estaba empezando a acercarme a un universo del conocimiento que me sorprendía, pero particularmente a entender la relevancia de hacer transformaciones radicales. Es ahí cuando empiezo a identificarme con la Revolución y de lo que implicaba entonces meterse en todos esos procesos. Mi familia, sin embargo, estaba muy distante de eso. Mi padrastro, que manejaba camioncito que surtía la Universidad de Antioquia, asumía que esos antropólogos eran unos marihuaneros y los más tira piedra, unos guerrilleros. Pero en general, mi decisión de estudiar antropología no implicó ruptura con la familia. Aunque era una decisión que ellos no entendían del todo, siempre han respetado. Con el tiempo, siento que admiran lo que he hecho. Ahora, llegó a la antropología por la política. Yo no llego a la antropología y después ya salto pensar en lo político sino que terminé en la antropología y en la universidad como parte de esos procesos y luchas que para los años ochenta eran muy fuertes en Colombia.

\item \personaje{Ignacio} y cómo te recibía ese fluido también, porque hoy día por ejemplo nuestras alumnas nuestros alumnos muchas veces viven en contextos donde la política está muy reprimida donde sobre todo en las zonas del Estado de México donde hemos tenido un mismo partido durante 90 años que recientemente salió y donde hay un entendimiento de las políticas como una forma de dijéramos de de vida en el sentido de de trabajo más que de verdad de ser política de transformación de cambios no y donde se ha anquilosado no...la famosa Revolución mexicana murió por el mismo por la misma Revolución que la mató. La convirtió en una forma el intercambio y tenemos juventudes que ahora afortunadamente a raíz de la desgracia de violencia de género y de diversidad que vivimos empiezan a politizarse, pero muchas veces no entienden o no son entendidas o entendidos en su politización como algo que se puede hacer en la universidad. ¿Si supiste que tuvimos un paro de 2 meses por nuestras alumnas y nuestros nuestras alumnas que tomaron las instalaciones por la violencia de género que había institucional? Y fue muy duro porque nos tocó ver una lectura de la universidad donde de repente compañeros y compañeras no entendían nada. Me recordaban mucho a frases de la dictadura española sobre cuestiones que tú dices bueno o el eficientísimo las personas muy preocupadas porque tal papel tiene que estar tal día y no siendo consciente de hasta dónde la política hoy... lo decía que en García Canclini que son muchas ese movimiento dolosos los que llevan la política pero ¿cómo vivís esa entrada?

\item \personaje{Eduardo} Nosotros en los 80 queríamos hacer la revolución. Eso es otro momento histórico realmente. No sé si se puede dimensionar la estructura del sentir, para usar ahí una expresión de Raymond Williams, en la que yo estaba inscrito. Una estructura de sentir donde queríamos hacer la revolución, queríamos hacer una transformación. Nosotros no entendíamos la cuestión de la política por fuera de nuestras vidas. Era parte de nuestras vidas y la universidad no estaba por fuera del mundo, no estaba en contra del mundo. La universidad era parte del mundo y nosotros estábamos en la universidad no para que nos dieran un título y nos habilitaran para trabajar de 8 de la mañana a 5 de la tarde y ganarnos un salario. Nosotros estábamos ahí por razones muy disímiles, pero muchos de nosotros queríamos que lo que hacíamos y lo que pensábamos se viera inscrito en una transformación del mundo. Una transformación que muchas veces pasaba por las armas, aunque para otra gente no. Pero era una cosa muy distinta a la de hoy donde la noción de violencia de las armas en relación con lo político es muy distinta. Hoy la noción de violencia armada ha sido vaciada de su dimensión ético política, se la ha circunscrito a unos empresarios de la muerte, se la ha moralizado, y se la ha psicologizado. A nosotros la política tenía que ver con nuestra vida y pasiones, era algo que buscaba transformar la mierda que estábamos viviendo. Para nosotros la política estaba en la vida y la vida era parte de nuestra universidad y de nuestra realidad.

\item \personaje{Ignacio} Claro en ese sentido me siento un poco reflejado.

\item \personaje{Eduardo} o ¿te tocó eso?

\item \personaje{Ignacio} Yo me centré mucho en los movimientos de ocupación estaba en los centros sociales y sí tenían y si veíamos esa parte. Sabíamos cómo incluso en mi licenciatura algunos de los trabajos fueron precisamente sobre la concepción del espacio de la ocupación. De por qué se rechazaba un centro comercial, por qué se rechazaba un centro cívico y cómo se se percibe la construcción de las realidades. Pero sí recojo esta idea del goce. Nuestra política era muy divertida, nosotros jugábamos contra la policía, estábamos proactivos. Nuestra música era política, pero era proactiva. La sentíamos como una cotidianidad que la llevaba tanto físicamente a través de la estética como culturalmente a través del arte y a través de la cotidianidad. No era la política es que a las 6:00 de la tarde en tal sitio tengo una asamblea no, sino que era una cotidianidad y además con cierta erótica. Había una erótica en la política que se compartía con los compañeros, con las compañeras no.

\item \personaje{Eduardo} Por aquí hay una expresión muy famosa de personaje que fue muy importante en el proceso del M19 que decía que la revolución es una rumba o no es... Mucha gente ha planteado cosas así.

\item \personaje{Ignacio} Claro y bueno teniendo en cuenta que obviamente la construcción política de Eduardo tiene mucho que ver con su contexto tiene mucho que ver con qué ocurre en Colombia. Estaría buenísimo que a raíz de esta entrevista muchas personas tratarán de conocer y de comprender las historias que tuvo Colombia y que sigue teniendo no ahora mismo se encuentra en un proceso de paz. Pero, por ejemplo, el ELN hasta donde yo sé no está en el proceso de paz. No hay una paz unívoca y hay mucho mucha precaución porque los de siempre siguen ahí. De hecho el tema de la propiedad de la tierra sigue siendo un problema pese a los supuesto acuerdos. Pero, por ejemplo, ¿cómo era la universidad que tú viviste? Está claro que tu universidad no era algo fuera de tu casa o fuera de tu ser, sino que era parte de la cotidianidad, pero ahora que vivimos en la época de las clases híbridas de los zooms de lo políticamente correcto de todo ¿cómo era la universidad a la que fue Eduardo en Medellín?

\item \personaje{Eduardo} Bueno muy diferente de lo que es hoy cualquier universidad. Primero los profesores no estaban ahí sintiendo que dar clases era algo que les quitaba tiempo para publicar papers que era lo que realmente importaba. En esa época la gente escribía y se publicaba, pero el propósito de los profesores ni de la universidad no era producir para satisfacer los indicadores de las burocracias académicas, no era no era acrecentar ese bulímico sistema del productivismo. Nadie estaba pensando en eso. Por otro lado, los estudiantes no estaban ahí pensando que eso era algo que los iba a habilitar para tener trabajo, ni papás les estaban pagando la matrícula, ni vivían con sus papás. Los estudiantes en esa época se comportaban como gente grande, muy autónomos, que se la rebuscaban de diferentes maneras. Era gente que tenía otra actitud. Con respecto a los cursos, se los asumía como lectura y discusión. Se leían otras cosas para complementar. Se iba mucho a la biblioteca y nos rodábamos los libros y las fotocopia. Ahora uno le pone a los estudiantes un programa y si el enlace de la lectura no le abre, llegan a clase diciendo que "no profe yo no leí porque no abrió". Los estudiantes ahora preguntan de qué página qué página leo. No se cuestionan por no llegar leídos y preparados para sus clases, y piden todo masticadito, clarito, sin muchas complicaciones. Lo que quiero señalar es que el ethos de estudiantes y profesores era muy distinto. Hoy prima en las universidades un modelo infantilizado y paternalista, el modelo de la universidad que tiene unos clientes a los que debe satisfacer y cuya prioridad es graduarse cuanto antes, lo más rápido y ojalá sin mucho esfuerzo. Por supuestos que hay excepciones, pero sin duda hay un cambio generacional profundo. Otra diferencia es que la universidad era una cosa donde se habitaba muchas horas. Uno llegaba muy temprano y se iban muy en la noche y no era porque tuviera todo ese tiempo clase, sino porque era un espacio donde sucedían muchas cosas: se conversaba, donde uno se enamoraba, donde uno tenía la posibilidad de aprender de la historia del país y de la universidad en las asambleas. Se discutía de política, de literatura, de psicoanálisis. O sea, era un espacio de formación en el sentido más profundo e integral de la palabra. Estuve nueve años haciendo mi licenciatura y me hubiera quedado 15 donde hubiera podido. Era un espacio donde se movían muchos procesos también. Uno se juntaba con otros combos acompañando procesos de campesinos, en los barrios populares y muchas cosas. Era una universidad muy vital, conectada con el mundo, siendo parte del mundo. Uno se llenaba de mundo literalmente ahí, y uno llegaba también con un mundo. Nada del modelo gerencial de universidad que han impuesto las burocracias que han ensimismado a la universidad, la han atiborrado de formatos que llenar y de reuniones sin mucho sentido, de subcomités de comités, del afán por tener unos indicadores de productividad que sueñan con que los legitime en estándares del norte global que responden a toda una geopolítica del conocimiento y a unas políticas de la ignorancia, que reproducen sin siquiera darse por enteradas.

\item \personaje{Ignacio} Y dentro de esa universidad en la que tuviste la suerte de formar conformar, interaccionar, construir, amar, disfrutar, jugar ¿qué era la antropología en Colombia? Porque una de las cosas que a lo mejor nuestros oyentes o las personas que lean esta entrevista no sepan, hay muchas antropologías y es una palabra excesivamente polisémica cruzada por el poder... Claro, ¿qué antropología tuviste la oportunidad de aprender?

\item \personaje{Eduardo} En ese momento en la Universidad de Antioquia había dos grandes concepciones de la antropología. Había una concepción más plegada a lo que significaba la antropología metropolitana, más pensada como ciencia universal, ciencia pura, neutral, objetiva que seguían muchos los parámetros de los de los de los grandes héroes culturales de la antropología francesa, estadounidense o inglesa. Tuve profesores y había compañeros que encarnaban esa versión de la de la antropología como ciencia, una ciencia pulcra, que buscaba ofrecer una serie de conocimientos a ser acumulados. La otra concepción, que se implicaba mucho con el pensamiento latinoamericano, era una antropología crítica, una que problematizada fuertemente el asunto de que la antropología estaba por fuera del mundo.

Complejizaba profundamente la idea de que la antropología tenía como propósito producir conocimiento antropológico en abstracto, sino que pensaba que el conocimiento antropológico se hacía por, para y en relaciones históricas y contextos concretos. Era una concepción muy política en el sentido de que la antropología era una práctica para la transformación social, con unos agentes en particular. Se cuestionaba mucho la idea de la verticalidad de la producción de conocimiento. En esta versión había muchas lecturas de América Latina se leía a Mariátegui, se leía Martí, se leía a Bonfil Batalla. Entonces que en los ochenta y principio de los noventa cuando yo estoy en en la Universidad de Antioquia, que fue del 87 que entre yo a el 96, hay dos visiones de la antropología: una universalista cientificista y una más anclada a lo a lo que puede ser el pensamiento crítico latinoamericano y más vinculada con la idea de lo político.

\item \personaje{Ignacio} De hecho todavía existen estas dos vertientes. Seguimos teniendo colegas que están anquilosados en una ciencia antropológica, departamentos de ciencias antropológicas con un neopositivismo, con una búsqueda formalista del conocimiento, y pues otra antropología más aplicada, más construida desde la cotidianidad desde la base más horizontal. Hay una cosa que me gustaría que pudiéramos reflexionar un poco, porque a nuestro alumnado muchas veces cuando le hablamos de problematizar es una palabra que no entiende a qué nos referimos con que la antropología problematiza situaciones. Muchas veces lo entienden como que las hacemos difíciles, ¿a qué te refieres cuando hablas de qué problematizamos la realidad desde esa antropología más crítica o más reflexiva?

\item \personaje{Eduardo} fundamentalmente a que desnaturalizamos aquello que se da por sentado. Es una invitación a una actitud reflexiva y de distanciamiento crítico con respecto a lo que se asume como dado. Entonces problematizar es cuestionarse por lo que uno no se pregunta porque lo da por sentado. Es algo así como que un pez se pregunte por el agua ya que seguramente, por su obviedad, el pez ni la ve y menos toma distancia de lo que implica.

\item \personaje{Ignacio} De hecho, muchas veces son las preguntas que más potencias tienen, ya que cuando eres capaz de problematizar algo que sea hegemónico, naturalizado, asumido, algo tan tonto como por qué me he levantado a las 6:00 de la mañana. Me refiero en el sentido incluso individual y personal. Creo que también te puede dar esta visión más crítica y más reflexiva de la antropología tanto como sujetos colectivos como a tu misma vida.

\item \personaje{Eduardo} Allí se junta la teoría y la posibilidad de la práctica. La teoría permite iluminar, los conceptos permiten afinar la mirada de forma que uno puede introducir distanciamientos críticos o digamos interrumpir aquello que fluye naturalmente en su obviedad. Entonces esa esa problematización: es un paso de la práctica política. El problematizar es parte de la política.

\item \personaje{Ignacio} Siguiendo un poco ese crecimiento personal y profesional también llega un momento en que, tras el salto, que además se puede leer desde muchas formas, porque sabemos esta famosa frase de que Latinoamérica, en la periferia, hacemos las etnografías y las teorías las hace en el norte global. ¿Cómo consigues llegar a la Universidad de Carolina del Norte en Chapel Hill? No eres el único. Hay muchos colegas que han pasado por esa universidad y hay algo que entiendo que te rompe un poquito la cabeza y que te mueve el tapete de repente cuando encuentras a determinada aproximación. Háblanos un poco de eso.

\item \personaje{Eduardo} ¿Cómo llega hasta allá un chico como yo de un barrio popular que quería ser sicario pero que no pudo serlo? La historia es larga y tiene muchos vericuetos, pero la voy a resumir. Cuando era estudiante de la Universidad de Antioquia, tuve la posibilidad de participar con la Universidad Nacional de Medellín en un proyecto de investigación muy grande que se conoció como Proyecto bosques guandal que se adelantaba en los ríos Satinga y Sanquianga. Esto es a comienzos de los años 90. En el marco de este proyecto hice mi trabajo de campo en antropología en el Pacífico sur colombiano. Terminé participando del proyecto bosques de guandal por la invitación de uno de mis amigos, y por quien realmente decidí estudiar antropología, que se llama David López. En el programa de antropología de ese entonces nosotros teníamos que hacer un semestre de campo, y la Universidad de Antioquia, por ser universidad pública, un semestre podría durar un año y medio o tres meses depende de cómo estábamos en las asambleas, los paros y demás. Como parte de mi trabajo de campo, Jorge Ignacio del Valle nos pidió que presentáramos una ponencia en el primer congreso sobre biodiversidad en Cali. Al simposio que asignaron mi ponencia, que era coordinado por Fernando Urrea, quien luego me invitó a una serie de talleres en la Universidad del Valle. Ahí conocí a Claudia Steiner, quien dirigía antropología social en el Instituto Colombiano de Antropología. Ella me dijo que cuando pasara por Bogotá, la visitara. Luego, cuando estaba revisando las fuentes para mi tesis de pregrado, fui a Bogotá hablé con Claudia, y así terminé contratado por el Instituto Colombiano de Antropología en 1994 hacer una serie de revisiones bibliográficas y demás. En ese contexto es donde conozco a Arturo Escobar, porque él estaba moviéndose por el Pacífico colombiano haciendo una investigación. Ahí nos conocimos y nos volvimos muy amigos. Para 1998, mi esposa quería hacer un doctorado en Estados Unidos y a Arturo nos apoyó para que ella se presentara y fue aceptada. Luego, en el 2000 me aceptan en el doctorado en la Universidad de Carolina del Norte, donde estaba Arturo como profesor. Entonces, en mucho mi llegada al doctorado allá fue por Arturo quien es un amigo muy querido, a quien que admiro y respeto. En Chapel Hill para mí fue fundamental conocer al Larry Grossberg, por quien pude dimensionar la relevancia de Stuart Hall. Conocía un par de artículos de Stuart Hall, lo había citado incluso en un texto sobre identidad y política tratando de entender el proceso de etnización de comunidades negras. Pero es cuando llego a Chapel Hill, en un seminario con Grossberg sobre introducción estudios culturales donde entiendo que Stuart Hall es más que un autor sobre identidad. El transitaba y había elaborado muchas de las cosas que resonaban con lo que hacíamos en los años 80 y 90 en antropología. Para mí es esta veta de los estudios culturales la que hace sentido y me parece relevante. La antropología estadounidense que vi en la mayoría de los seminarios en el doctorado era más solmene, más academicista, más bulímica en términos de textos y de citas, en cambio estudios culturales en esta vertiente insisto, era muchos más potentes: esa idea de la politización de la teoría y la teorización de lo político, lo de la intrincación de la labor intelectual para la transformación social, eso sí resonaba. De forma muy muy escueta la historia te estoy resumiendo 15 años...

\item \personaje{Ignacio} Sí, sí, estamos hablando de una vida.

\item \personaje{Eduardo} Una vida, sí, sí.

\item \personaje{Ignacio} Pero fíjate que es una cosa que siempre llama mucho la atención no sea muchas veces existen las prácticas, tienes una construcción y de repente aquí en México como que te cae el 20. O sea repente encuentras algo que tú no sabías que estaba ahí y encaja con lo que tú pensabas, que se podía y se debía hacer. Y ese es un momento de enamoramiento puro y duro.

\item \personaje{Eduardo} Para utilizar una metáfora musical: lo que estaban haciendo Hall y Grossberg era como la salsa donde me sentía como en casa, que podía bailar y apreciar. Antes de llegar a estudiar el doctorado ya tenía cierta familiaridad con la antropología estadounidense, porque si una cosa tiene uno en América Latina es que lo forman en todas las tradiciones académicas metropolitanas. Desde entonces he estado enamorado de Stuart Hall, para mí ha sido profundamente inspirador. Lo sigo leyendo y releyendo. Incluso confieso que lo he traicionado al posicionarlo en el establecimiento académico hispanoamericano (ya que para comienzos de los dos mil no se lo conocía mucho). Y digo traicionado porque lo peor que uno le puede hacer a Hall es academizarlo. No obstante, en mi defensa puedo argumentar que, con esta universidad putrefacta, en este momento de una academia descorazonada y ensimismada, poner a circular a Hall es una bocanada de oxígeno para el pensamiento.

\item \personaje{Ignacio} No, pues es lo bello. Precisamente yo también te confieso que he tenido alumnas y alumnos qué se enamoraron de tus textos que de repente les pasé. Cuando me piden algo de etnografía recomiendo ese pequeño libro tan cómodo, tan bien que escrito que tú nos regalaste. Ayer estuve en una defensa de ciencias de la salud, una nutrióloga que venía de un mundo hiper cuantitativo de individualización de la salud, y que tomó un curso conmigo de antropología de la alimentación. Le dije: más que antropología alimentación por qué no te lees a Eduardo, ve lo que está hablando sobre la interacción social humana y después vas a campo. Ayer nos dijo en el tribunal que "habéis cambiado mi vida..."

\item \personaje{Eduardo} Muy potente. Son asuntos como esos, los que llenan de verdadero sentido a lo que uno hace.

\item \personaje{Ignacio} Que es exactamente, pero es lo mismo que con Stuart te pasa a ti. Muchas veces no somos conscientes de que vamos soltando cartas en el océano o botellas con mensajes y alguien la recoge y dice "es que esto era lo que yo necesitaba para lo que llevo dentro, porque no había encontrado un vehículo y algunas personas os convertís casi en medios para llegar a entenderse a sí mismo y a entender. Siempre considero que la antropología nos coloca ante este tipo de cuestiones, es un proceso también muy de de entenderse a sí mismo.

\item \personaje{Eduardo} ¡Por supuesto! Usaba la palabra de inspiración, porque eso es lo que producen autores como Hall Admiro en Hall, por ejemplo, su coherencia entre lo que planteaba y lo que hacía en su vida. Es que uno puede encontrar autores que escriben o hablan cosas muy relevantes, pero muchos son profundamente incoherentes con lo que son en sus vidas, con la manera en que encaran sus prácticas ético-políticas. ¿Para qué tanta teoría si no se concreta en la vida propia, si termina uno haciendo las mismas babosadas que hacía sin ella?

\item \personaje{Ignacio} Pero Eduardo...

\item \personaje{Eduardo} Siempre me he imaginado participando en conversaciones asociadas al campo de los estudios culturales y también de la antropología.

\item \personaje{Ignacio} Y un montón de tradiciones también, porque para buscar antropólogos...

\item \personaje{Eduardo} Mi relación con la antropología es una relación en la que la he amado profundamente, pero por eso mismo la he criticado radicalmente. Desde mucho antes de viajar a Estados Unidos, entre 1995 y 1997 armamos en el Instituto Colombiano de Antropología una crítica radical a la antropología colombiana que se concretó en una colección de publicaciones titulada Antropología en la modernidad. En ese momento cuestionamos lo que llamamos indiología (que en México todavía define mucho de la imaginación antropológica más convencional). Lo que te quiero decir es que mi relación con la antropología, precisamente porque uno la aprecia y la ama, es una de crítica radical. Hay muchas cuestiones la antropología que ameritan ser desmontadas, hay muchas cosas profundamente conservadoras y profundamente fuera del lugar. Lo mismo con estudios culturales. Me muevo cuestionando el grueso del establishment de los estudios culturales. A menudo hábito un lugar de disidencia, entre otras cosas porque mi posición política es anarquista.

\item \personaje{Ignacio} Se lee entre líneas, te entiendo. De hecho, esa es la posición ideológica que yo también comparto. Dentro de las contradicciones de estar en una universidad pública, estatal, pero cuando estaba en la Universidad de Sevilla había algunos colegas que hicieron un trabajo sobre antropología anarquista, y tenemos a Graeber, tenemos determinado tipo de planteamiento que en última instancia a mí lo que lo que me refería es esta gracia de cómo cuando aparecen los estudios culturales la disciplina se posiciona no y de repente dice: no, no, la cultura es nuestra, nadie puede estudiar la cultura sino es la antropología; y hay una reacción muy fuerte contra los estudios culturales. Recuerdo en licenciatura algunos profesores maldecían a los estudios culturales, pero no entendíamos realmente como un alumno de licenciatura, no comprendías cuál era el problema. Bueno, si esta gente está haciendo eso. Ahora entramos en la otra cosa que le gustaría hablar contigo que tienes una forma muy interesante de entender la práctica etnográfica, no como un patrimonio de la antropología sino como una forma de interacción social. ¿Por qué nos hablas de un poquito de eso?

\item \personaje{Eduardo} La antropología no deberíamos entenderla como una disciplina igual en todas partes y tiempos, como esencia que siempre ha estado y estará hasta el fin de los tiempos garantizada por una problemática (como la alteridad) unos temas o unas metodologías. Me parece más potente pensar que pensar a la antropología como una, en singular, desde una lectura esencialista de la disciplina, es uno de los efectos de canon instalado, pero las antropologías realmente existentes (que han sido desde siempre múltiples) operan en entramados institucionales que están, entre otras cosas, muy atravesadas por sensibilidades nacionales. Entonces, por ejemplo, la manera como la antropología se relaciona con estudios culturales e México, en Argentina o en España o en Brasil no es la misma que se puede dar en Colombia. Lo que quiero decir es que en México los estudios culturales producen cierto un escozor entre los antropólogos lo mismo que en Argentina, aunque por razones distintas. En México porque la antropología ha sido estatalizada, monumentalizada, la antropología mexicana ha estado vinculada a un establecimiento estatalizado, que es solemne, y que se imaginó desde retoricas antropológicas como la figura del mestizo, o esa celebratoria de la monumentalidad prehispánica en contraste con políticas de integración y borramiento de la indianidad actual. La antropología mexicana tiene un lugar en el imaginario nacional incomparable al de ningún otro país. Lo que implica en México el museo de antropología no existe en ninguna otra parte del mundo. Desde esta particular articulación de la antropología en México, entonces los estudios culturales se piensan como usurpadores, como una monstruosidad en las márgenes: sí, son dos locos allá en Iztapalapa, pero eso no es "antropóloga de verdad". En Colombia existen 12 maestrías en estudios culturales, y la relación de estudios culturales es muy distinta porque la antropología en Colombia no se constituye en términos del establecimiento y del imaginario nacional de la misma manera que en México. Las antropologías ancladas en el establecimiento académico en Colombia están muy abiertas a la conversación con las teorías sociales contemporáneas, no se han enconchado en la indianidad. En la Argentina hay también un escozor fuerte con estudios culturales porque allá son percibidos como posmodernismo light, como una moda yanqui, que dada su aprecio por el estilo intelectual francés (y brasileño, que es también en mucho afrancesado) los coloca en una situación de profunda sospecha. Lo que quiero decir es que la relación entre antropología y estudios culturales depende de la particular configuración de los establecimientos académicos y las tradiciones intelectuales, con todos capitales simbólicos que entran en juego ahí. Por otro lado, me parece importante pensar en términos de antropologías disidentes. Hay una larga historia de América Latina de desnaturalizar lo que aparece y lo que se anuncia como antropología. Existen muchas conversaciones. En México está lo de Esteban Krotz con antropologías en y del sur. En Brasil lo de antropologías centrales o metropolitanas y periféricas con Cardoso de Oliveira. En algún momento, con Gustavo Lins Ribeiro, Arturo Escobar, Marisol de la Cadena y mucha otra gente, pensamos lo llamamos antropologías del mundo y antropologías del mundo. Esto de antropologías del mundo es un encuadre que lo que busca es preguntarse por las relaciones de poder que constituyen la visibilidad o invisibilidad, la hegemonizarían o la subalternalización, de determinadas antropologías. Esa conversación que es muy larga como para presentar ahora, pero inspirado en la teoría queer y en el anarquismo vengo elaborando la noción de antropologías disidentes: esto es, antropologías que ni siquiera aparecen como antropología desde los criterios que constituye el canon como lo propiamente antropológico en un gesto normalizante que clausura disidencias, derivas, líneas de fuga, irreverencias. Pero bueno, esa es otra larga conversación.

\item \personaje{Ignacio} Es una conversación muy interesante de hecho había permitido... Antes de pasar a este tema, me voy a permitir leer, hemos tenido la suerte de reeditar dos tomos panorama de la antropología mundiales, de nuestro colega y amigo Gustavo Lins, quien hizo la edición general y bueno tenemos aquí también a Carmen Bueno, Virginia Laura, gente que yo quiero mucho, que conocí cuando llegué a México, y que realmente se aproximado mucho más a lo que yo entendía como antropología que otras personas. Hay un párrafo que voy a leer que me parece muy potente para para nuestro alumnado y para los colegas también: "las cegueras y silenciamiento de unas tradiciones sin embargo no pueden ser entendidas adecuadamente como simples ignorancias maniqueas de unos antropólogos en ciertos países del norte que perversamente quieren desconocer sus colegas en establecimientos antropológicos periféricos. En primer lugar porque muchas de estas cegueras y silenciamientos son compartidos y abiertamente reproducidos por los colegas y los establecimientos periféricos" Esta idea es fascinante y además podríamos cambiar la palabra antropología por sociología, por física, por cualquier forma de conocimiento en el siglo XXI. Es una de las cosas que dentro de la idea del anarquismo como un elemento liberador, y de cultura y de forma de conocimiento subyace porque, en última instancia, los amos del conocimiento no son amos porque sean omnipotentes.

\item \personaje{Eduardo} Sí, ni dios ni amo... como el anarquismo. Las políticas de la ignorancia son producidas desde lo que aparece como conocimiento y qué no, qué es relevante y qué irrelevante, quiénes son leídos, cómo son leídos y cómo son incluso apropiados: eso no es natural, sino que es el resultado de una geopolítica del conocimiento, hacen parte de unas prácticas que asumen que algo es conocimiento desde una intervención normalizante del canon, al tiempo que producen desconocimiento, marginalización o invisibilización. Ahora eso no es tan malo desde una perspectiva queer y anarquista ya que desde ahí una lectura digamos más convencional de luchar unas políticas de la visibilización, de que nos reconozcan, es perder de vista que el verdadero tropel está en otro lado, apunta en otra dirección.

\item \personaje{Ignacio} Pero ese no sería el problema para mí. El problema no es que nos conozcan o no, y eso yo creo que lo compartimos, es que no los conocemos a ellos o sea este el juego perverso último de esta exotización, de esta periferización. Vamos, ahhh sí, pero nadie nos conoce. O sea, se dedican a orientalizaciones, pero ¿qué ocurre con esos amos del conocimiento?, ¿por qué no estamos haciendo el mismo proceso con los grupos hegemónicos y solo nos dedicamos a estudiar subalternos por todos lados?

\item \personaje{Eduardo} sí esa es una arista que es muy importante. Hemos hemos centrado mucho de nuestro esfuerzo en estudiar a sectores subalternizados porque es una práctica con una inercia que se afinca en un conjunto de relaciones de poder y, a menudo, lo que hace es introducir una otrerización, exotización, una serie de efectos digamos de apropiación y de expropiación de cierto tipo de conocimiento. Tenemos que pensar más a los poderosos, a los sectores dominantes, a las clases políticas y empresariales, tenemos que conocer más al poder, tenemos que desnudar las filigranas y obscenidades del poder, y a nosotros mismos en los entramados de poder, porque es que el poder no es una cosa que está allá afuera, no es una substancia o una cosa como nos lo ha invitado a pensar Foucault, sino que nos implica de muchas formas, nos constituye como expertos, como antropólogos. Gústenos o no, nos demos cuenta de eso o no, hacemos parte de los engranajes de la dominación. Entonces también tenemos que orientar más la mirada hacia arriba y hacia los lados, y dejar de estar mirando hacia abajo. Esas cosas son profundamente problemáticas. Sí hay un montón de discusiones sobre la geopolítica del conocimiento, pero también sobre la política de la ignorancia. Lo que leías ahorita del libro de Gustavo no es solo es que o que hacemos en las antropologías periféricas realmente no les importa (ni siquiera a nosotros, todavía mas tristemente porque estamos mirando siempre al norte global), sino que ese desconocimiento se hace con una impunidad y arrogancia imperial.

\item \personaje{Ignacio} Puede ser interesante sobre todo para nuestro alumnado porque una de las cosas que me he dado cuenta es que nuestra práctica tiene muchas palabras que alejan a la gente. Recuerdo una vez que estaba con unos pastores en la sierra y de repente se acercan y dicen oiga eso de gastropólogo ¿qué es? Porque utilizamos palabras muy densas y que para mí ocultan cosas mucho más básicas y se escuchan mucho más simple. Entonces ¿cómo explicaríamos a personas que a lo mejor estudia en biología ambiental o que estudian ingeniería qué es una etnografía.

\item \personaje{Eduardo} Una etnografía es devenir en entendimiento desde la gente... es estar realmente con la gente... tratar de entender una pregunta o una temática desde la perspectiva de la gente con la que uno se involucra en una etnografía. Entonces la etnografía es muy potente porque implica un conjunto de prácticas de saber estar y fluir en escenarios y con las personas con las que estamos trabajando, pero también nos permite un conocimiento que no se puede entender de otra forma. Uno no puede entender el mundo en esa riqueza que tiene en consideración las perspectivas de otra gente si uno no se involucra desde la vida en serio con esa gente. Cuando uno es visita a uno lo tratan de una forma y uno solo puede experimentar ciertas cosas, establecer unos tipos de conversaciones. Para acercarse a entender el mundo como como la gente lo experimenta, para devenir desde la gente, implica ir mucho más allá. Entonces la etnografía de la manera más más simplista decirlo más concreta es devenir en entendimiento desde la gente, lo que toma su tiempo, supone ciertas habilidades, y nos constituye mutuamente. No se hace etnografía impunemente, sin ser tocado e interpelado.

\item \personaje{Ignacio} Y a la hora de estar con la gente, ¿cómo es este ejercicio en el cual tienes que procesar y ser consciente de quién eres y de cómo? Porque también para muchas personas que es la reflexividad, que Rosana Guber la trabaja muy bien y nos explica que de repente, cuando empiezas a hacer etnografía no solamente es estar con la gente, sino que muchas veces, cuando de verdad empiezas a entenderte y a comprenderte y necesitas ser consciente de tu cuerpo, de tu voz, de hasta de tu hambre ¿cómo funciona para Eduardo ese proceso? Cuando tienes el lujo, porque cada día la etnografía como práctica es cada vez es un lujo, más difícil de seguir.

\item \personaje{Eduardo} Claro...bueno ahí hay varias cosas. Primero, es muy importante que ese estar en serio con la gente implique un ponerse en cuestión a sí mismo. Un ejemplo concreto obvio se refiere a abrirse con la comida, con la dormida, con el cuerpo, con los chistes; o sea ese tratar de estar en serio con la gente pasa por tomar distancia de esos lugares de confort y de certezas que lo constituyen a uno. Esto no significa borrarse a sí mismo, ni tampoco de que no se establezcan límites. Entonces del lado de uno hay un cuestionamiento de lo que ha sido o ha asumido. Es una relación implicación, de ser interpelado. Eso vale la pena escribirlo el diario de campo que es también es un espacio para hablar con uno mismo, no solamente para registrar lo que está sucediendo, lo que uno ve o encuentra, sino para hablar consigo mismo. Una etnografía es ante todo una relación social, es un proceso social uno es impactado y transformado. La etnografía no es solo una modalidad de producir conocimiento. Para mí la etnografía no es simplemente un asunto epistemológico, de producción de conocimiento, si no que es fundamentalmente una relación social que te implica como etnógrafo, y de la cual se deriva el posicionamiento ético-político. Por otro lado, lo de que cada vez más hacer etnografía es un lujo o un privilegio también depende mucho. Ahorita hablamos de que tenemos que estudiar más el poder. Pero para adelantar estas etnografías no se puede o debe apelar al modelo de estar en serio con la gente pues toca hacer muchas adecuaciones, darle la vuelta a la cosa. Es más, una consideración ética trabajando con una comunidad en términos etnográficos no puede ser equivalente a una consideración ética trabajando con un grupo paramilitar, por ejemplo. Aunque en este último caso también hay dimensiones éticas, no puede operar de la misma manera. Lo que quiero decir es que es que sí es un lujo en el sentido de pasar largos periodos de vida compartiendo la cotidianidad de unas personas. Eso es cierto, sobre todo en este establecimiento bulímico que anda desquiciado produciendo papers, cuando no llenando los formatos para poder si quiera inscribir un proyecto de investigación. También tenemos que considerar que cada vez más contamos con otras posibles fuentes y escenarios de relacionamiento que pueden contribuir al enriquecimiento de la labor etnográfica, como por ejemplo lo digital. Esto no se puede pensar como una sustitución o reemplazo del trabajo de campo más convencional. No lo remplaza, pero lo potencia de una forma impresionante, incluso en investigaciones clásicas que no tienen que ver directamente preguntas sobre lo digital. Tenemos que diseñar etnografías que incorporen de formas creativas lo digital. Esto puede ser decisivo en etnografías que buscan desnudar el poder y requieren muchas veces de abordar oblicuamente las temáticas. Una cosa final, uno puede estar 200 años en un lugar y no ver nada, no entender etnográficamente ese lugar. La etnografía no es simplemente estar, la etnografía implica una actitud, pero también implica unas buenas lentes teóricas y de sensibilidad que permiten que ese estar produzca entendimientos enriquecidos de ese mundo que encara. Entonces no es simplemente tiempo, pero es en mucho cuestión de tiempo. La etnografía es como el vino, toma su tiempo... un tiempo con otros, por lo que no es simplemente un asunto del tiempo propio. Me preocupa, en relación con esto, que he leído algunos artículos, trabajos de grado o informes que dicen que hicieron etnografía cuando lo que hicieron fue unas entrevistas o unos talleres (o los famosos focus groups), cuando estuvieron un par de semanas, cuando mucho en terreno. Eso no puede ser etnografía. No todo trabajo de campo es etnográfico, no toda entrevista es etnografía.

\item \personaje{Ignacio} Claro, estoy totalmente de acuerdo y lo cierto es que a muchas personas eso les cuesta no sea por sobre todo es la cotidianidad. Últimamente consiste en no estar, todo lo que hacemos es escapar, todo lo que hacemos es desconectarnos y de repente, como hablaba yo con un colega de la universidad de Sevilla, con David Lagunas sobre el tema del método abductivo, que está también ahí no solamente lo inductivo y lo deductivo. Pero lo lo difícil que se está convirtiendo por la incapacidad que estamos teniendo cada vez más de conectar, de abrir, de observar, de interaccionar. Si quieres bajamos un poco a una parte que también es muy interesante para para nuestros oyentes para las personas que están ahí y para quienes pueden leer porque ¿quién es Eduardo Restrepo hoy, como persona?

\item \personaje{Eduardo} Un viejito

\item \personaje{Ignacio} Un viejito jajaja... ¿qué es lo que tu vida académica ha hecho de ti o tú has hecho de ella?

\item \personaje{Eduardo} Ahorita estoy en un momento de ruptura con asuntos que hice durante mucho tiempo. Estuve trabajando 16 años en la Universidad Javeriana, y hace 2 años largos renuncié a la Universidad Javeriana. Mi renuncia fue texto público en el que argumentaba por qué me iba. Hay cosas que no se pueden negociar y yo no podía ocupar para los curas el lugar del esclavista de unos profesores de cátedra que eran contratados en condiciones precarias, mientras otros colegas se rascaban el ombligo en una aridez intelectual y decidía monumentales. Es un asunto digamos ético-político, yo no podía estar ahí manteniendo otra gente en una relación de precariedad mientras a mí me pagaban un dineral. Por otro lado, renuncie porque se querían meter con la producción de los contenidos y la querían mantener en una plataforma que ellos controlaran. Querían que los contenidos se produjeran en la misma universidad. Es que los curas entienden la universidad como un colegio grande. Para mí la universidad es autonomía, disenso y libertad de catedra... no hay nada que hacer, eso no es negociable y los contenidos no negociables. Entonces renuncie de manera irrevocable e inmediata, y ha sido una de las mejores decisiones que he tomado en mi vida. Me vine a vivir a Tumaco, una pequeña isla al sur de Colombia en el Pacífico colombiano. Por aquí he estado yendo y viviendo durante más de treinta años. Aquí siento que puedo aportar muchas cosas, tiene más sentido dirigir tesis, dictar unos cursos presenciales, compartir libros y bibliografía, conversar también sobre asuntos académicos de los que poco se habla. Además, tengo amigos desde hace más de treinta años, con los que ya compartimos historias de vida. Estoy en un momento de la vida en el que prefiero estar más desligado del establecimiento académico, del cual cada vez siento que es un cadáver, uno en putrefacción que apesta, plagado farsantes. El establecimiento académico hace mucho rato perdió el sentido que alguna vez tuvo, parece que mucha la gente que está ahí no tiene sangre en las venas, priman las burocracias académicas con sus arrogancias y angustias en torno a indicadores de productividad y calidad que en ultimas a nadie le importa, y los estudiantes muchos se piensan como clientes y vienen a compras sus títulos, quieren salir cuanto antes, pagan para que les escriban sus trabajos (ahora seguro que cada vez menos con la IA), que añoran un trabajo en una oficina de ocho a cinco, con una buena paga, con aire acondicionado o calefacción. Por eso estoy en un momento de distanciamiento con eso. Estoy haciendo todo etnografía sin afanes y sin burócratas que me pidan llenar formatos. Una etnografía sin premuras y sin plazos, que va fluyendo con la vida.

\item \personaje{Ignacio} Bueno también lo que algunas personas comentaban que, en cierto sentido, es un privilegio poder alcanzar esa posición y esa renuncia no que siempre tenemos que poner sobre la mesa ¿no?

\item \personaje{Eduardo} ¡Total! es un privilegio, pero es uno que gestamos desde prácticas concretas en asuntos que pasan por tomar ciertas decisiones y asumir sus consecuencias, para bien o para mal. Yo podía seguir estando ahí en la Javeriana, vegetando como casi todos los profesores de planta de mi departamento, y recibiendo un muy buen salario, con la jubilación y las prestaciones de salud aseguradas. Vi marchitarse a un par de talentosos colegas, porque se cagaban del miedo de que los echaran o que se quedaran sin trabajo. Siempre hay pretextos para excusarse a uno mismo (están los hijos, los préstamos, el futuro..., y de personas que escriben asuntos radicales, con análisis sobre la dominación y las resistencias, las epistemologías otras... ¡qué triste!). Creo que hay que tomar decisiones para darle prioridad a las cosas que realmente importan. Toca pararse. Es fácil languidecer en áridas reuniones, corriendo a más no poder para satisfacer el ultimo capricho de los burócratas, encorvándose pusilánimemente mientras lo relevante se pasa.

\item \personaje{Ignacio} A eso me refería en el sentido del privilegio en todas las acepciones de la palabra. No solamente desde una posición privilegiada laboralmente podemos hablar, sino desde una posición también ética, política y el tiempo se dio. Muchas personas estamos en la carrera académica, y aunque estemos bueno en mi caso fuera de mi país y todo el tema es un privilegio que no es realmente vivido como tal sino en cierto sentido, yo recuerdo cuando gané la plaza en la metropolitana, que tenía un sentimiento muy encontrado porque después de haber vivido en cuatro o cinco países de repente tenía una plaza base, o sea eso quiere decir que me voy a quedar en México el resto de mi vida, y ya llevo 10 años. Entonces son cosas que también muchas veces están ahí no y que incluso prefieren no irte porque es cómodo dijéramos. El estar ahí, el hacer tus articulitos, tu no sé qué. Y la vida sigue. También el poder mirarte con honestidad y poder decir algo, corte de caja y hasta aquí no. Ahora precisamente hiciste un poco salto en la escaleta porque es una cosa que a mí me preocupa mucho y de hecho nos preocupa a muchos colegas. Este devenir que está teniendo la universidad como institución en sí, como su función social, la simplificación que ha tenido. Obviamente...la universidad que yo viví en los años noventa no tiene nada que ver con la que viviste tú a lo mejor a comienzos de los noventa y finales de los ochenta en Colombia, pero no tiene nada que ver con la que yo estoy viviendo ahora. Somos una unidad que es joven, tiene 14 años aproximadamente, pero donde vemos continuamente que nuestro alumnado viene en las dos horas que tiene de clase y si llega tarde y se va antes casi que mejor. Donde tenemos colegas que los cubículos están vacíos porque prefieren no venir y que lo pueden hacer todo desde su casa. Entonces de repente encontramos en la metáfora de esqueletos no vacíos, ¿cómo ves la universidad o qué universidad ves porque tu experiencia también puede ser muy muy variada por haberte movido tanto por lo que decías de que eres un viejito... ¿es algo general o sea es un proceso?

\item \personaje{Eduardo} Es un proceso general que tiene que ver con asuntos generacionales pero también con transformaciones políticas e institucionales. En términos generacionales, las últimas dos generaciones tienen sensibilidades y prioridades muy distintas de las anteriores. No quiero plantear que las de antes eran mejores que estas ultimas o al revés, pero sí es un hecho que son muy distinta. Por ejemplo, recuerdo los últimos cursos que dicté en la Universidad Javeriana en pregrado (licenciatura o grado, en otros países). Desde que entraban en el primer semestre, ya planeaban todo para graduarse cuando antes. Se mostraban muy ansiosos sobre que trabajos iban a tener, cuánto les pagarían y demas asuntos que a nosotros ni se nos pasaban por la cabeza. Eso lo habiamos resuelto o lo resolveriamos de otra forma, realmente no nos importaba eso mucho. Los estudiantes de hoy viven con sus papás. También se debe a cuestiones de clase social, sin duda. Pero ahí encontramos un cambio sustancial en cuanto a lo que nos mantiene estudiando antropología o cualquier otra profesión. He notado, ademas, el contraste generacional en términos de cómo abordar la lectura de un texto o la escritura. Hoy uno se encuentra con una actitud infantilizada, dependiente y muy creyentes de lo que los profesores digan en clase. Lo de la socialización. Nuestros tiempos eran muy distintos, y pues lo que tú estás diciendo Ignacio.Ahora los estudiantes andan muy ocupados. Nosotros también pero de todas maneras estábamos ahí. Pues no sé las redes sociales ha facilitado cosas pero también han complejizado muchos asuntos. La pasión por la lectura, por la escritura, por la conversación cara a cara, por escuchar, esas cosas como que no ya cada vez son más extrañas. Ahora hay que decirles qué tienen que leer exactamente...

\item \personaje{Ignacio} no, no o sea...

\item \personaje{Eduardo} y de que párrafo a que párrafo, y qué tengo que entender y qué entra en el examen o en el trabajo...

\item \personaje{Ignacio} y lo peor no es eso. Lo peor es cuando dicen, pero tenemos que leerlo o hay algún resumen. Oye, ¿cómo que si tenemos que leerlo o sea...?

\item \personaje{Eduardo} Pero detrás de eso hay unas transformaciones que hay que pensar ...

\item \personaje{Ignacio} romantizar buenos tiempos...

\item \personaje{Eduardo} Sí, no caer en la tramapa de los buenos viejos tiempos, que suelen ser idealizaciones aplanadas. Hay transformaciones que entran en juego en lo que es la universidad hoy. También los profesores de las universidades hace algunas décadas eran menos afanados, disfrutaban ser profesores, estaban más yo siento y lo trataban a uno como un par. Ajora los profesores son más de distantes, más ensimismados, más ansiosos por responder a un montón de requerimientos de la burocracia académica que se les come todo el tiempo. Si uno examina lo que uno dedicaba en términos de tiempo para responder a los caprichos de la burocracia universitaria hace unos 15 años no es nada con respecto a los entrampamientos burocraticos que experimentan hoy cualquier profesor. Antes incluso la burocracia estaba en función de los profesores y los docentes, estaban para responder a asuntos concretos. Hoy se han tomado la universidad, sus caprichos son inapelables. Parece que a nadie le importara realmente la docencia, que han encorcetado en formatos de planificacion, de seguimiento, de evaluacion, de mejoramiento... formato tras formato, reunión tras reunión, una reunión para planear otra reunión, y subcomité de un comité: es absurdo. El antropólogo anarquista Dadid Graeber publico un libro maravilloso que aborda estas insensateces que ya hemos naturalizado y que nos socavan nuestras existencias. El libro se titula: Trabajos de mierda. Entonces creo que los profesores también han cambiado mucho, están muy llenos de ansiedades y muchos pareciera que realmente odiaran dar clases y a los estudiantes. En México es una risa cómo todo el mundo esta es pendiente del certificado, de su ponencia, de su asistencia. Los brasileños ni se diga. Ahora los profesores y estudiantes corren tras sus certificados, de todo: leen un texto y el certificado, dirigen una tesis y el certificado. La interacción en las universidades ahora es muy distinta. Hay cosas muy positivas pero también hay un montón de arandelas de las cuales es vital no propiciar ninguna ambigüedad. Soy de los profesores que suelo decir que la vida es dura y si alguien no entrega o hace un trabajo mal le pongo su nota de reprobación. Se quieren morir, y hasta traen a la mamá. Suponen que hay que evaluarlos por sus intenciones y esfuerzos, no por los resultados. Escriben terrible, copian y pegan a diestra y siniestra en ocasiones de mala fe, y ahora con la IA es impresionante. Todo esto tiene que ver con la con la con los cambios institucionales, que la burocracia académica se entronizó y lo que importa en una universidad es lo que la burocracia académica impone. Eso no simplemente depende de una universidad sino que está encadenado a las entidades estatales nacionales y todos los intereses económicos y de capital simbolico en las enormes casas editoriales del norte global. El lugar central de la burocracia y sus ansiedades en las universidades nos ha vaciado el sentido mismo del trabajo intelectual, nos ha arrabatado lo que lo que era fundamental era la relación profesor-estudiante. Todo esto ha suscedido en un proceso de neoliberalización de las universidades, de la ciencia y la tecnologia en nuestros países, pero tambien de las subjetividades de profesores y estudiantes que se han convertido en emprezarios de sí. No he conocido ninguno de estos burocratas que logré dimesionar que supondria hacer universidad en un país latinoamericano porque tiene la cabecita los modelos que le que le plantean en Harvard. Las universidades se han convertido en industrias de titular estudiantes, como en las promociones en los supermercados les ofrecen un título o dos, en un tiempo estipulado, para que como clientes se sientan satisfechos. Por todo eso la universidad dejó de ser un escenario para pensar, y menos un escenario para trasformar políticamente el mundo.

\item \personaje{Ignacio} Pero sin embargo, lo necesitamos como un espacio de pensamiento y de transformación. O sea ¿cómo ves Latinoamérica hoy?

\item \personaje{Eduardo} El anarquismo es un camino cada vez relevante. Pero no veo al anarquismo en la universidad porque este es un espacio diseñado para que las jerarquias y el autoritarismo fluya. Además, honestamente muchos de nuestros colegas son parte del problema, son en parte responsables del vaciamiento de significado político real, no el de los comunicados firmados por internet o los acomodamientos linguisticos o de la adecuada pose del momento. Muchos colegas están dichozos publicando sus papers y recolectando certificados, no pocos de los cuales escriben en un tono crítico y con gran fluidez teórica sobre las luchas de los sectores subalternizados, de los movimientos sociales, del feminismo, del racismo, de la decolonialidad o del eurocentrismo.

\item \personaje{Ignacio} Es precisamente en esa línea que a mí me preocupa muchísimo Latinoamérica hoy. Precisamente en la universidad era un espacio de resistencia y de existencia y de respuesta, y ahora tenemos una Latinoamérica en la que Milei accede al gobierno de que Argentina, ganando además holgadamente en muchos lugares, donde hemos tenido la situación en Brasil de la destrucción que provocó el gobierno de Bolsonaro, donde zonas de la selva, zonas de reserva indígena, han sido destruidas y en en los pocos años. Tanto en México como en otros países estamos en proceso de militarización. Hemos tenido la noticia de que los los aeropuertos civiles pasan a ser controlados por los militares. Procesos de despojo donde la población local es repelida o desaparecida incluso o asesinada por el por el ejército y por el narco. Entonces ¿qué está ocurriendo en Latinoamérica? ¿Hacia dónde va Latinoamérica? Crecí escuchando en mi casa a Víctor Jara, sonaba la Negra, sonaban esas canciones que me hablaban de una Latinoamérica, que me daba envidia, porque lo que teníamos allá era una salida a una dictadura con un gobierno que se decía de izquierda y que lo que hacía era desmontar todo lo que oliera a horizontalidad, a lucha social, a derecho para convertir a España en lo que se convirtió, que es una un chiringuito de playa para Europa prácticamente. Y ahora resulta que en Latinoamérica estamos como estamos ¿cómo ves todo este mundo todo lo que nos está ocurriendo?

\item \personaje{Eduardo} Empezar por decir que la universidad y los académicos somos muy responsables en América Latina de lo que está pasando. Nos estamos sorprendiendo algunos de las cosas, pero somos parte del problema de lo que está sucediendo nos atañe por no haber tropeliado con claridad, con organización y fuerza la imposicion de modelo gerencial en nuestras universidades y en las instancias estatales destinadas a la ciencia, la tecnologia y la educación. Para no hablar de los cientos de colegas que han estado en cargos publicos y politicos locales, regionales y nacionales que no hicieron realmente la diferencia más allá de ciertos acomodamientos cosmeticos. Uno puede tener la impresión que Milei apareció de un día para otro, pero es parte de una serie de procesos que están por fuera de la universidad usualmente, de configuración de redes y de disputas no solamente de discursos sino de sensibilidades, de emocionalidades, de maneras de organizar e interpelar a gentes de carne y hueso. No lo vimos porque nuestras universidades están muy ensimismadas en unos lugares de confort, con muchos doctores y doctoras que publican papers y se pasean por hoteles cuatro o cinco estrellas, donde se realizan anualmente esperpentos como los congresos de LASA o de la AAA. El modelo de universidad que se ha consolidado como dominante en nuestros países reproducen una fractura esquizofrénica: una mimesis y plegamiento a una academia definida por criterios del norte global que contrasta con las urgencias y el mundo de la vida de mucha gente en nuestra región. Por eso insisto que la universidad y los académicos son parte del problema en América Latina y, como dice Ochy Curiel, por ahí no va a pasar ninguna transformación política relevante. Para acabar de empeorar la situación se ha ido imponiendo una narrativa y una práctica de de lo que llamamos orgullosamente producción de conocimiento, que básicamente es un montón de lugares comunes, puros comités de aplausos de lo que nosotros, en un cerramiento moral que clausura analisis concretos y contextuados, consideramos esencialmente buenos como las comunidades, el movimiento social, las mujeres, las victimas, indígenas, afrodescendientes, sexualidades no normativas, migrantes... Por esto, en las universidades, como el mundo oenegero, ciertas instancias estatales y de la jurisprudencia, se va a consolidar el buenismo, sin duda; cada vez son más raros los colegas que no se portan bien. No obstante, esta operación de clausura de un pensamiento sin garantias para recurrir a Hall está implicando cada vez más la clausura el pensamiento por el cerramiento moral de la política. Confunde lo partista (la toma de partido por los buenos) con lo político, que es otro asunto. En la academía prima una imaginacion politica no va mas alla de versiones más o menos consistentes con el liberalismo, con algunos socialdemocratas por ahí colados, cuando no de posiciones conservadoras y de derechas, cada vez más envalentonadas.

\item \personaje{Ignacio} Bueno coincido prácticamente en todo. Estamos atrapados en sistemas de dominación pero desde una comodidad excepcional. Recuerdo siempre una frase de la izquierda española que decía: siempre que contra Franco vivíamos mejor. Y ahora parece que realmente si no llegamos a unos puntos en los que la derecha en sus múltiples formas estéticas, políticas o como le queramos decir aprieta más. Hay una cosa, que por ejemplo está pasando en España, es absurdo. Cómo el PSOE que en realidad es de centro derecha no es de izquierdas, pero cómo toda su política de perdón a la derecha, que parece que da vergüenza hacer determinados tipos de acciones. Es como, bueno, entonces para qué está tu programa, dónde está esa construcción que quieres hacer de la sociedad, dónde está la transformación que se supone que podemos obtener a través de ti. Y vuelve a esta idea de que en el fondo los planteamientos socialdemócratas son una invención de la derecha para desactivar a la izquierda y para que al final estemos en un supuesto bienestar que lo que hace básicamente es desactivar. Hay una cosa que también recojo que es todo este fetichismo que tenemos hacia los derechos, como un fin en sí mismo, cómo reconócerme y dame. Bueno, vivo en un país que tiene muchas leyes y que tiene muchísimos derechos y no sirven para nada. Entonces por qué esa obsesión con el fetiche de poner en un papel que yo puedo ser, en vez de ser...Terminan siendo artefactos de sistemas de dominación, muy eficientes porque no solamente alteran el objetivo de la lucha sino el medio de la lucha, para luego conviertirse en un proceso burocrático administrativo en el que tengo que conseguir que papá estado me dé un papel, que diga que existo y para qué quieres existir.

\item \personaje{Eduardo} Le das un lugar de interlocución al Estado tal en el cual eres en tanto te enuncie, y seguro lo hará en sus términos... en ocasiones antecediendo subjetividades politicas que luego circulan como dadas desde los albores de los tiempos. Ignacio dos cosas que nos están enseñando las derechas emergentes ahora a nosotros. Uno es que se enuncian orgullosa y claramente de derecha. Eso significa que las izquierdas no pueden encubrirse en relatos que posan de centros sino reivindicar sus tradiciones y legados, pero también diferencias (porque el anarquismo no es estalinismo), ni mucho menos ir concediendo asuntos de principios que no son negociables en aras de caerle bien a todo el mundo.

\item \personaje{Ignacio} y perdona, la otra incluso antes entres a ese punto, es que parece que hay que pedir perdón y sea por tener un planteamiento político que no se acerca al establishment dijéramos a esta hegemonía, tiene que darte pena lo que dije, hay que estar como pidiendo perdón.

\item \personaje{Eduardo} O sea la política es eso, tomar posición desde unos criterios que configuran un campo de confluencias, pero también de luchas y disputas.

\item \personaje{Ignacio} y fíjate que aquí volvemos a volvemos al punto primero originario cuando tú decías y hablábamos de la violencia...cómo la violencia se moraliza, se monopoliza y se institucionaliza y ya. Pareciera que la violencia sólo la puede ejercer la derecha y el Estado. Y bueno entonces nosotros ¿a base de abracitos vamos a conseguir algo? ¿Con firmas en change.org vas a conseguir que la gente tenga agua, vas a conseguir que podamos respirar en las ciudades? No, creo que no...

\item \personaje{Eduardo} Y la historia no nos ha enseñado eso...Lo otro que nos ha enseñado, y aquí yo quisiera parafrasear a Hall, cuando un decía que Margaret Thatcher probablemente no había leído una línea de Gramsci, pero que lo que hacia ella en parecía que lo entendía mejor que toda la izquierda británica que se había pasado años leyendo y discutiendo a Gramsci. A nosotros nos está pasando lo mismo en el campo de los estudios culturales o en eso que se denomina pensamiento crítico en América Latina. Personajes como Agustín Laje o Javier Milei están trabajando en la disputa del sentido común, lo tienen claro: lo llaman la batalla cultual. Y lo están haciendo de que han interpelado a sectores de jóvenes o le han dado sentido a malestares de movimientos conservadores. Mientras se mueven con sus cursos, conferencias, analisis, libro en las plataformas y en eventos en ocasiones multitudinarios, nosotros encerraditos en conferencias en congresos para leer en diez minutos una ponencia, a la que ni a veces asisten tus amigos que están en el mismo congreso, y pagas un dineral para que te entreguen el certificado, que es lo único que en la práctica importa para entregárselo juiciecitos al burócrata de turno.

\item \personaje{Ignacio} y ya para ir cerrando un poco ¿cómo ves como ves a Eduardo o dónde deja Eduardo o haciendo que de aquí a 10, 15, 20 años?

\item \personaje{Eduardo} ¡Muerto!... ya estaré muerto. No vivimos por siempre

\item \personaje{Ignacio} pues claro ahora ya vivimos por siempre ¿por qué aquí no?

\item \personaje{Eduardo} Yo quisiera terminar de escribir un par de cositas y ya...Siento que la vida es eso: estar un tiempo a hacer unas cosas que la hacen merecedora de haber sido vivida, y ya. Quisiera cerrar un par de texticos que aún requieren trabajo. Quisiera estar apoyando de una manera muy marginal procesos. No quisiera estar en cargos visibles al frente de cosas, sino haciendo la labor sucia que usualmente no le gusta hacer a muchos colegas como dirigir tesis y dictar unas clasesitas con pasión.

\item \personaje{Ignacio} Pues muchísimas gracias por tu tiempo y muchas gracias por...

\item \personaje{Eduardo} No, a ti.

\item \personaje{Ignacio} Por esta charla, por este cafelito que hemos podido disfrutar metáfora y pues seguimos en contacto. Esperamos esos texticos que tú dices que tienes que terminar. Seguro que lo leeremos con mucho gusto, mucho placer. Aquí desde la UAM, desde la Metro, pues te mandamos un fuerte abrazo con todo el cariño y deseamos que sigas viviendo la vida que quieres vivir.

\item \personaje{Eduardo} ¡Muchas gracias, Ignacio!

\item \personaje{Ignacio} Hasta luego.
\end{transcripcion}
