project:
  type: book

book:
  title: ""
  chapters:
    - index.qmd
    
lang: es

format:
  html: default
  pdf:
    documentclass: scrbook
    pdf-engine: xelatex
    include-before-body: portada.tex
    toc-title: "Índice"
    reference-section-title: "Referencias Bibliográficas"
    lof-title: "Índice de Figuras"
    lot-title: "Índice de Tablas"
    toc: true
    number-section: false